### ISSUE TITLE
👀

### ISSUE THREAD

**Issue by JediMasterSoda** [CVunderscore/Epic#4]
CVunderscore/Epic#1

**Comment by CVunderscore** [comment]
![picture-13164-1528972253](https://user-images.githubusercontent.com/33987907/83350216-7b6f5a00-a2ef-11ea-92f4-ae75b9f284f0.png)

**Comment by JediMasterSoda** [comment]
Duplicate of #1

**Comment by JediMasterSoda** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/6241454/83350233-59ca9e80-a300-11ea-9df4-2cda5494d70a.png)

**Comment by CVunderscore** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/6241454/83350233-59ca9e80-a300-11ea-9df4-2cda5494d70a.png)
> 
> Thanks github....

Yeah this aint goin fly buddy
